server:
  port: 80

spring:
  application:
    name: demo
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# ====================== ↓↓↓↓↓↓ MinIO文件服务器 ↓↓↓↓↓↓ ======================
minio:
  url: http://127.0.0.1:9001
  accessKey: admin
  secretKey: password
  bucketName: test
