# seata配置
seata:
  # 是否开启seata
  enabled: true
  # Seata 应用编号，默认为 ${spring.application.name}
  application-id: ${spring.application.name}
  # 是否开启数据源代理
  enable-auto-data-source-proxy: false
  data-source-proxy-mode: AT
  # Seata 事务组编号，用于 TC 集群名
  tx-service-group: test-tx-group
  # 服务配置项
  service:
    # 事务组和cluster的映射关系
    vgroup-mapping:
      test-tx-group: default  # 值需与seata服务端中nacos配置的`cluster`值保持一致
    # 分组和 Seata 服务的映射
    grouplist:
      default: 127.0.0.1:8091
  config:
    type: nacos
    nacos:
      serverAddr: ${spring.cloud.nacos.config.server-addr}
      group: SEATA_GROUP
      namespace: ${spring.cloud.nacos.config.namespace}
      username: ${spring.cloud.nacos.config.username}
      password: ${spring.cloud.nacos.config.password}
      dataId: seata-server.properties
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: ${spring.cloud.nacos.config.server-addr}
      group: SEATA_GROUP
      namespace: ${spring.cloud.nacos.config.namespace}
      username: ${spring.cloud.nacos.config.username}
      password: ${spring.cloud.nacos.config.password}

# 数据源配置见：application-db.yml
#spring:
#  datasource:
#    dynamic:
#      seata: true    # 开启seata代理，开启后默认每个数据源都代理，如果某个不需要代理可单独关闭
